language: node_js
addons:
  firefox: "47.0"
node_js:
  - "6"
matrix:
  fast_finish: true
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
env:
  - TF=test
  - TF=addons/Dexie.Observable/test/unit
  - TF=addons/Dexie.Observable/test/integration
script:
  - npm run build
  - cd $TF
  - pwd
  - bash ./travis.sh
