language: node_js
addons:
  firefox: "66.0"
node_js:
  - "8"
matrix:
  fast_finish: true
services:
  - xvfb
env:
  - TF=test
  - TF=addons/Dexie.Observable/test/unit
  - TF=addons/Dexie.Observable/test/integration
  - TF=addons/Dexie.Syncable/test/unit
  - TF=addons/Dexie.Syncable/test/integration
  - TF=addons/dexie-export-import/test
  - TF=test/integrations/test-dexie-relationships
script:
  - npm run build
  - cd $TF
  - pwd
  - bash ./travis.sh
